### ISSUE TITLE
进行任何操作时都会显示“目标计算机积极拒绝，无法连接”

### ISSUE THREAD

**Issue by MineTestGaming** [ArknightsAutoHelper/ArknightsAutoHelper#165]
![屏幕截图(24)](https://user-images.githubusercontent.com/73379450/107136506-d22d3900-693e-11eb-8453-9bb168cff087.png)
试过打开之前用adb devices连接，但是没有用

**Comment by HaneRo** [comment]
在配置文件中修改客户端ip及端口
