### ISSUE TITLE
公开招募识别 “近战位” 识别为 “近位”

### ISSUE THREAD

**Issue by HaneRo** [ArknightsAutoHelper/ArknightsAutoHelper#166]
此错误进出现在该标签在左下角时，没有发现在其他位置出错的情况

**Comment by HaneRo** [comment]
![Screenshot_20210216-125249](https://user-images.githubusercontent.com/26104114/108020603-ae14da80-7057-11eb-8176-18b563d71915.png)
commands (prefix abbreviation accepted):
    quick [+-rR[N]] [n]
        重复挑战当前画面关卡特定次数或直到理智不足
        +r/-r 是否自动回复理智，最多回复 N 次
        +R/-R 是否使用源石回复理智（需要同时开启 +r）
    auto [+-rR[N]] stage1 count1 [stage2 count2] ...
        按顺序挑战指定关卡特定次数直到理智不足
    collect
        收集每日任务奖励
    recruit [tags ...]
        公开招募识别/计算，不指定标签则从截图中识别
    exit
akhelper> recruit
 Ξ 确认设备名称：10.10.10.96:5555
 Ξ 识别招募标签
 Ξ 可选标签：近卫干员 医疗干员 先锋干员 近位 新手
Traceback (most recent call last):
  File "Arknights\shell_next.py", line 220, in interactive
  File "Arknights\shell_next.py", line 181, in recruit
  File "Arknights\helper.py", line 608, in recruit
  File "Arknights\recruit_calc.py", line 29, in calculate
ValueError: 未知 tag: 近位

**Comment by yuanyan3060** [comment]
正常现象，ocr识别率有限，项目组又懒得自己训练。

**Comment by chunibyo-wly** [comment]
![image](https://user-images.githubusercontent.com/33208530/127444924-90dc6c25-46b2-4830-be81-debdf0b87f35.png)

tesseract 4.1.1 无法复现
