### ISSUE TITLE
日服的文字识别问题

### ISSUE THREAD

**Issue by Yorafa** [ArknightsAutoHelper/ArknightsAutoHelper#182]
![image](https://user-images.githubusercontent.com/61265053/112513988-3e3af380-8d6b-11eb-8845-e12dbdac1570.png)
![image](https://user-images.githubusercontent.com/61265053/112514269-84905280-8d6b-11eb-9d82-4cc36418577c.png)
如图，关卡消耗为15，且在第一张图中实际理智为106。
详细：为了适配日服，我下载了源码，并修改了两张图片以便于简单的快速刷取。但是在文字识别方面，日服时字体不同还是什么不同，会将1识别成4或3，请问在代码的哪里可以进行修改呢，同时我怎么才能知道我用的是什么ocr呢，我在config中设置了百度的api，但是识别方面好像并没有任何区别。请问这些数据值在yaml中，是要加引号还是不加引号呢?
此外如果我如果整理好了图片，该怎么pull呢？

**Comment by dantmnf** [comment]
理智识别用的是土制简单 OCR，可以考虑替换成通用 OCR：
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/b5a3a89011de030632b6280f05ee7654b3987d07/imgreco/before_operation.py#L36-L40

通用 OCR 用法：https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/b5a3a89011de030632b6280f05ee7654b3987d07/imgreco/common.py#L98-L99

当前只有对话框识别和公开招募识别使用了通用 OCR，各种后端的优先顺序在 README 和配置里有说明。YAML 里字符串没有与其他数据类型产生歧义的时候可以省略引号。

适配外服可以参考 https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/wiki/Porting-to-Another-Server ，目前也不打算在这个 repo 里支持外服，因为实在是没有精力去维护，可以考虑自己维护一个 fork。

**Comment by klarkxy** [comment]
https://github.com/klarkxy/ArknightsAutoHelper
分支jp
我自用的日服分支
可以参考使用
