### ISSUE TITLE
gui打开会在桌面新建浏览器图标 能否关掉

### ISSUE THREAD

**Issue by Noomnus** [ArknightsAutoHelper/ArknightsAutoHelper#285]
gui版打开后 在桌面生成了edge的浏览器图标 删除后 下次打开又会新建 能否去掉   命令行模式没有问题

**Comment by dantmnf** [comment]
看起来是 edge 的云控恶臭推广😅

建议安装 Chrome 或者 [Chromium](https://chromium.woolyss.com/)，~~或者我这边再带一个 Electron~~

**Comment by Noomnus** [comment]
默认浏览器换了Chrome和套皮chromium也不行---- 回复的原邮件 ***@***.***>发送日期2022年01月01日 11:39 ***@***.***> ***@***.******@***.***>主题Re: [ninthDevilHAUNSTER/ArknightsAutoHelper] gui打开会在桌面新建浏览器图标 能否关掉 (Issue #285)

看起来是 edge 的云控恶臭推广😅

建议安装 Chrome 或者 Chromium，或者我这边再带一个 Electron



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/issues/285#issuecomment-1003496829",

"url": "https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/issues/285#issuecomment-1003496829",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by dantmnf** [comment]
Chrome/Chromium 应该是比 Edge 有更高优先级并且不遵循默认浏览器设置的（会创建一个独立 profile），但是只会尝试搜索默认安装位置。

可以尝试在配置文件里指定为 Chrome：
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/ba5641322493be4c6245cc62378fc766ccbbad59/config/config-template.yaml#L108-L115

**Comment by Noomnus** [comment]
谢谢 我试一下---- 回复的原邮件 ***@***.***>发送日期2022年01月02日 14:29 ***@***.***> ***@***.******@***.***>主题Re: [ninthDevilHAUNSTER/ArknightsAutoHelper] gui打开会在桌面新建浏览器图标 能否关掉 (Issue #285)

Chrome/Chromium 应该是比 Edge 有更高优先级并且不遵循默认浏览器设置的（会创建一个独立 profile），但是只会尝试搜索默认安装位置。

可以尝试在配置文件里指定为 Chrome：

https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/ba5641322493be4c6245cc62378fc766ccbbad59/config/config-template.yaml#L108-L115



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/issues/285#issuecomment-1003670903",

"url": "https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/issues/285#issuecomment-1003670903",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
