### ISSUE TITLE
用于台版使用时卡在等待确认编队

### ISSUE THREAD

**Issue by Arcelibs** [ArknightsAutoHelper/ArknightsAutoHelper#300]
adb connect 127.0.0.1:3122
正在返回主页
已回到主页
进入作战
选择类别
目标 PR-C 坐标=[1584.75  351.75] 差异=0.008088
目标 PR-C-1 坐标: [585. 618.]
目标在可视区域内，点击
当前理智 4596, 关卡消耗 18
理智充足 开始行动
等待确认编队
等待确认编队
等待确认编队
等待确认编队
等待确认编队
等待确认编队
等待确认编队
8 次检测后不再确认编队界面
未能进行第 1 次作战
已忽略余下的 4 次战斗

已經將resources\imgreco\before_operation\operation_start.png 替換為台版的圖片
![operation_start](https://user-images.githubusercontent.com/49543451/151688882-3a89a996-45c7-458b-95dd-687fa0aa047f.png)

**Comment by dantmnf** [comment]
图片需要在固定位置截取，可以尝试直接保存 log/imgreco.before_operation.html 中的图片
