### ISSUE TITLE
第十章更新后不可用

### ISSUE THREAD

**Issue by sanosenx86** [ArknightsAutoHelper/ArknightsAutoHelper#326]
第十章更新后无法识别关卡结束界面、设置代理界面以及第十章，希望大佬更新一下

**Comment by li494391537** [comment]
因为UI布局更新了

**Comment by sanosenx86** [comment]
是的是的，希望更新一下

**Comment by enldm** [comment]
四点刚更新我就觉得用不了了...一直在选中代理指挥

**Comment by lchilin** [comment]
![delegation_checked](https://user-images.githubusercontent.com/52390867/163415956-a30b99b6-25f1-4cd3-a401-dff4f0bd6abf.png)
可以把这个图片复制到 ArknightsAutoHelper-master\resources\imgreco\before_operation\ 下面 
名称是  delegation_checked.png
能暂时解决 
后续的话还是等更新

**Comment by enldm** [comment]
> 

感谢帮助

**Comment by dantmnf** [comment]
已适配新 UI
