### ISSUE TITLE
收取制造站及贸易站功能有错误

### ISSUE THREAD

**Issue by FSeagle** [ArknightsAutoHelper/ArknightsAutoHelper#327]
![image](https://user-images.githubusercontent.com/37961319/163558092-94dcbdb9-403d-4375-b0d0-4644eb20b678.png)
以上是bug图
![image](https://user-images.githubusercontent.com/37961319/163558140-74068fd3-becc-4d7f-aeae-3b34c3f0e1a7.png)
但我界面是有蓝色标签的
我怀疑是不是因为这个红色标签把蓝色的顶下去了导致bug？

**Comment by dantmnf** [comment]
之前截的图都匹配不上了，非常神秘

总之重新截了一波，看起来是修好了
