### ISSUE TITLE
方舟客户端更新主旋律后刷当前关卡功能出错

### ISSUE THREAD

**Issue by ArkURL** [ArknightsAutoHelper/ArknightsAutoHelper#329]
一直在同一个关卡中反复选中和取消代理模式，无法进入关卡编队页面从而开始作战。
在使用gui和不使用gui的模式下都会出现同样错误。
![image](https://user-images.githubusercontent.com/56484166/163591621-a7108b02-bc2b-425c-9f8a-5ebbe7fd91c5.png)

**Comment by dantmnf** [comment]
fixed in 4b879c6d955d327afa1039f10e6ddb7c54bdb5f6
