### ISSUE TITLE
战斗结算界面报错

### ISSUE THREAD

**Issue by BearTartare** [ArknightsAutoHelper/ArknightsAutoHelper#332]
战斗结束

离开结算画面

Traceback (most recent call last):
  File "Arknights/addons/combat.py", line 314, in on_end_operation
  File "imgreco/end_operation.py", line 267, in recognize
  File "imgreco/end_operation.py", line 422, in recognize_20220414
RuntimeError: possibly incomplete item list

第 1 次作战完成

不在关卡界面

不在关卡界面

不在关卡界面

不在关卡界面

不在关卡界面

不在关卡界面

不在关卡界面

8次检测后都不再关卡界面，退出进程

未能进行第 2 次作战

已忽略余下的 9997 次战斗

-------------------------------------------------------------------------------
游戏画面停留在战斗掉落结算界面。不是每次战斗都会触发，雷电模拟器64，1280*720

**Comment by dantmnf** [comment]
请提供一下 log/ArknightsAutoHelper.log

**Comment by BearTartare** [comment]
[ArknightsAutoHelper.log](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/files/8500796/ArknightsAutoHelper.log)

**Comment by dantmnf** [comment]
a63863109bee0a9be2ff0137420e8ab68a12fad6 改了一个可能触发的地方，可以测试一下。

**Comment by BearTartare** [comment]
应该解决了
