### ISSUE TITLE
GUI不时卡死

### ISSUE THREAD

**Issue by sanosenx86** [ArknightsAutoHelper/ArknightsAutoHelper#337]
Windows10 64bit 21H2 
Chrome Version 100.0.4896.127 (Official Build) (64-bit)
GUI打开后时不时会卡死，卡死之后不会自动恢复，已提交的任务会继续执行，可以通过浏览器打开http://127.0.0.1:52257/?token=1145141920
看起来不是后端问题
卡死补图：
![image](https://user-images.githubusercontent.com/44931458/164914312-d9072fc2-e87c-43ed-b7b6-29e2ca765c88.png)
能否麻烦定位解决一下？虽然影响不大（启动任务就挂机了【

**Comment by dantmnf** [comment]
内嵌 webview 的锅，新版本已经禁用了

**Comment by sanosenx86** [comment]
更新之后完全无法启动了……二进制包，bootstrapper好像不对劲

初次启动的时候：
![image](https://user-images.githubusercontent.com/44931458/164948264-06d7ddfd-4e1b-4577-bf78-f6a70bc98dd1.png)

第二次及之后启动的时候：
![image](https://user-images.githubusercontent.com/44931458/164948204-2c8e98c9-4b87-4175-bd9b-aa3166f8d013.png)

是因为app还没打包发吗？

**Comment by dantmnf** [comment]
ci 打了包没发布，现在好了
