### ISSUE TITLE
新活动愚人号(SN)适配问题

### ISSUE THREAD

**Issue by arthurbroy** [ArknightsAutoHelper/ArknightsAutoHelper#341]
问题如下：
1. OCR识别时，对关卡（测试是SN-8）消耗理智识别有误，导致不能进行自动作战
2. 指定关卡作战时，不支持SN开头的关卡
3. 战利品列表里，对新物品“金币”的识别有误

根据log猜测，关卡名与消耗理智的OCR识别位置有问题，麻烦修复一下，感谢！
[log.zip](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/files/8599251/log.zip)

**Comment by dantmnf** [comment]
截取定位已修复，物品识别需等待识别模型自动更新（https://github.com/triwinds/arknights-ml/actions ）

关卡导航正在做，但是可能无法支持 720 分辨率。
