### ISSUE TITLE
为什么自动运行一段时间后游戏回自动闪退？

### ISSUE THREAD

**Issue by div2009** [ArknightsAutoHelper/ArknightsAutoHelper#351]
日志

> 

Ξ 已进行 103.5 s，判断是否结束
 Ξ 战斗结束
 Ξ 掉落识别结果：[SV-9] 声望&龙门币奖励: 龙门币x216; 常规掉落: 全新装置x1, 腐蚀的伊比利亚唱片x18
 Ξ 目前已获得：龙门币x3888, 腐蚀的伊比利亚唱片x324, 全新装置x8, (家具)x1
 Ξ 离开结算画面
 Ξ 第 23 次作战完成
 Ξ 当前理智 90, 关卡消耗 18
 Ξ 理智充足 开始行动
 Ξ 确认编队
 Ξ 等待 96 s
 Ξ 已进行 89.6 s，判断是否结束
 Ξ 已进行 103.1 s，判断是否结束
 Ξ 战斗结束
 Ξ 掉落识别结果：[SV-9] 声望&龙门币奖励: 龙门币x216; 常规掉落: 腐蚀的伊比利亚唱片x18
 Ξ 目前已获得：龙门币x4104, 腐蚀的伊比利亚唱片x342, 全新装置x8, (家具)x1
 Ξ 离开结算画面
 Ξ 第 24 次作战完成
 Ξ 当前理智 73, 关卡消耗 18
 Ξ 理智充足 开始行动
 Ξ 确认编队
 Ξ 等待 96 s
 Ξ 已进行 101.3 s，判断是否结束
 Ξ 战斗结束
 Ξ 掉落识别结果：[SV-9] 声望&龙门币奖励: 龙门币x216; 常规掉落: 腐蚀的伊比利亚唱片x18
 Ξ 目前已获得：龙门币x4320, 腐蚀的伊比利亚唱片x360, 全新装置x8, (家具)x1
 Ξ 离开结算画面
 Ξ 第 25 次作战完成
 Ξ 当前理智 55, 关卡消耗 18
 Ξ 理智充足 开始行动
 Ξ 确认编队
 Ξ 等待 95 s
 Ξ 已进行 98.2 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 111.7 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 127.7 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 139.3 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 152.1 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 167.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 181.4 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 196.0 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 210.5 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 223.4 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 237.5 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 251.0 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 263.9 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 279.1 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 292.0 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 306.3 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 319.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 332.7 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 346.2 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 360.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 373.3 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 387.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 400.5 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 412.3 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 426.1 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 439.0 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 453.5 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 466.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 479.0 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 491.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 504.9 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 518.0 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 531.2 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 544.2 s，判断是否结束
.....
Ξ 已进行 759.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 772.5 s，判断是否结束
 Ξ 战斗未结束
Traceback (most recent call last):
  File "automator/launcher.py", line 175, in command_internal
  File "automator/launcher.py", line 304, in cli_handler
  File "Arknights/addons/combat.py", line 416, in cli_quick
  File "Arknights/addons/combat.py", line 119, in combat_on_current_stage
  File "Arknights/addons/combat.py", line 389, in operation_once_statemachine
  File "Arknights/addons/combat.py", line 253, in on_operation
  File "automator/mixin.py", line 41, in delay
  File "automator/launcher.py", line 47, in delay
  File "automator/fancycli/fancywait.py", line 106, in fancy_delay
  File "automator/fancycli/win32.py", line 54, in getch_timeout
KeyboardInterrupt
akhelper adb:127.0.0.1:7555>
运行到20+次数以后就会自动闪退 不管是用MUMU模拟器还是用逍遥模拟器都会有这种问题 最后我只有手动退出循环

**Comment by dantmnf** [comment]
活动结束了，问题解决（
