### ISSUE TITLE
Bluestacks 5 (win11 Hyper-V) 下屏幕布局变化导致无法正常识别

### ISSUE THREAD

**Issue by Prurite** [ArknightsAutoHelper/ArknightsAutoHelper#354]
如下 log 及截图
![图片](https://user-images.githubusercontent.com/44775584/173263069-b3138ad3-180b-4f00-826a-d0c6af1cab46.png)
[ArknightsAutoHelper.log](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/files/8887211/ArknightsAutoHelper.log)

另1：我的 Bluestacks 在运行 adb connect 之后就画面卡死声音正常，虽然和这个脚本无关，但是有人遇到过相似的情况吗
另2：终于高考考完了，新电脑到手，这几天把校测考完之后就能来写代码了

**Comment by dantmnf** [comment]
部分模拟器不兼容新的截图方式，表现为截图全黑、退出进程之后依然卡死等，参考 https://arklights.vercel.app/guide.html#%E8%AE%BE%E5%A4%87%E5%85%BC%E5%AE%B9

目前正在重构 adb 部分，给每个设备 id 单独设置截图方式，但是真要能用估计得等新 GUI（

**Comment by Prurite** [comment]
> 部分模拟器不兼容新的截图方式，表现为截图全黑、退出进程之后依然卡死等，参考 https://arklights.vercel.app/guide.html#%E8%AE%BE%E5%A4%87%E5%85%BC%E5%AE%B9
> 
> 目前正在重构 adb 部分，给每个设备 id 单独设置截图方式，但是真要能用估计得等新 GUI（

参考那边的帮助把 Bluestacks 的图形引擎设置为兼容性模式后就能用了
不知道它又在整什么东西
