### ISSUE TITLE
最新版本运行会报错

### ISSUE THREAD

**Issue by Minepig** [ArknightsAutoHelper/ArknightsAutoHelper#359]
使用的是win二进制包，命令行启动，无论做什么都会报AttributeError

![image](https://user-images.githubusercontent.com/30530115/175290600-2aee4fb1-b0fa-4fec-a585-9b06b72ec586.png)

**Comment by dantmnf** [comment]
请暂时使用自动连接（不指定 `127.0.0.1:5555`）

**Comment by Minepig** [comment]
> 请暂时使用自动连接（不指定 `127.0.0.1:5555`）

我需要同时运行三个模拟器，自动连接似乎不能正确连接对应的模拟器
