### ISSUE TITLE
macOS Monterey安装时报错

### ISSUE THREAD

**Issue by tonysyz** [ArknightsAutoHelper/ArknightsAutoHelper#362]
Python Version:
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 16:55:45) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
设备：MacBook Air (M1, 2020)
系统：macOS Monterey(12.4 beta 5)
```shell
pip3.9 install onnxruntime
```
会报错：
```
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```
解决方案：
尝试过：重装Xcode command-tool、更换Python版本等
最终（应该）有用的是：
手动编译安装（https://github.com/microsoft/onnxruntime/issues/11037）
[download here](https://storage.asswecan.org:9443/f/f4b7fb28b2f74709a76e/?dl=1)
下载后：
```shell
pip3.9 install /path/to/onnxruntime-1.11.0-cp39-cp39-macosx_12_0_arm64.whl

```

**Comment by Lmcabu** [comment]
Hi, 请问您那还有这个.whl文件吗？这个链接过期了
